/* eslint-disable */
export type Token =
  | 'colors.main.black'
  | 'colors.main.yellow'
  | 'colors.grey.10'
  | 'colors.grey.20'
  | 'colors.grey.30'
  | 'colors.grey.40'
  | 'colors.grey.50'
  | 'colors.grey.60'
  | 'colors.grey.70'
  | 'colors.grey.80'
  | 'colors.etc.white'
  | 'colors.etc.focus'
  | 'colors.etc.error.10'
  | 'colors.etc.error.20'
  | 'colors.etc.error.30'
  | 'colors.etc.active.10'
  | 'colors.etc.active.20'
  | 'colors.etc.active.30'
  | 'colors.colorPalette.black'
  | 'colors.colorPalette.yellow'
  | 'colors.colorPalette.10'
  | 'colors.colorPalette.20'
  | 'colors.colorPalette.30'
  | 'colors.colorPalette.40'
  | 'colors.colorPalette.50'
  | 'colors.colorPalette.60'
  | 'colors.colorPalette.70'
  | 'colors.colorPalette.80'
  | 'colors.colorPalette.white'
  | 'colors.colorPalette.focus'
  | 'colors.colorPalette.error.10'
  | 'colors.colorPalette.error.20'
  | 'colors.colorPalette.error.30'
  | 'colors.colorPalette.active.10'
  | 'colors.colorPalette.active.20'
  | 'colors.colorPalette.active.30';

export type ColorPalette = 'main' | 'grey' | 'etc' | 'etc.error' | 'etc.active';

export type ColorToken =
  | 'main.black'
  | 'main.yellow'
  | 'grey.10'
  | 'grey.20'
  | 'grey.30'
  | 'grey.40'
  | 'grey.50'
  | 'grey.60'
  | 'grey.70'
  | 'grey.80'
  | 'etc.white'
  | 'etc.focus'
  | 'etc.error.10'
  | 'etc.error.20'
  | 'etc.error.30'
  | 'etc.active.10'
  | 'etc.active.20'
  | 'etc.active.30'
  | 'colorPalette.black'
  | 'colorPalette.yellow'
  | 'colorPalette.10'
  | 'colorPalette.20'
  | 'colorPalette.30'
  | 'colorPalette.40'
  | 'colorPalette.50'
  | 'colorPalette.60'
  | 'colorPalette.70'
  | 'colorPalette.80'
  | 'colorPalette.white'
  | 'colorPalette.focus'
  | 'colorPalette.error.10'
  | 'colorPalette.error.20'
  | 'colorPalette.error.30'
  | 'colorPalette.active.10'
  | 'colorPalette.active.20'
  | 'colorPalette.active.30';

export type Tokens = {
  colors: ColorToken;
} & { [token: string]: never };

export type TokenCategory =
  | 'aspectRatios'
  | 'zIndex'
  | 'opacity'
  | 'colors'
  | 'fonts'
  | 'fontSizes'
  | 'fontWeights'
  | 'lineHeights'
  | 'letterSpacings'
  | 'sizes'
  | 'shadows'
  | 'spacing'
  | 'radii'
  | 'borders'
  | 'borderWidths'
  | 'durations'
  | 'easings'
  | 'animations'
  | 'blurs'
  | 'gradients'
  | 'breakpoints'
  | 'assets';
