name: Storybook Develop Deployment
on:
  push:
    branches:
      - develop

jobs:
  storybook-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Preview
        run: |
          curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK_STORYBOOK_DEVELOP }}
